name: CD

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          version: "0.7.13"

      - run: uv run mkdocs gh-deploy --force

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Create Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          uv run cz bump --yes --changelog
          git push --tags
          uv run cz changelog --unreleased-version "v$(uv run cz version --project)" > RELEASE_NOTE.md
          gh release create "v$(uv run cz version --project)" -F RELEASE_NOTE.md --generate-notes
          NEW_VERSION=$(uv run cz version --project)
          echo "NEW_VERSION=${NEW_VERSION}" >> $GITHUB_ENV

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            k0wojtasinski/mimicry:${{ env.NEW_VERSION }}
            k0wojtasinski/mimicry:latest
