name: CD

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          version: "0.7.13"

      - run: uv run mkdocs gh-deploy --force

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Get project version from uv
        id: get_version
        run: |
          VERSION=$(uv version | awk '{print $2}')
          echo "version=$VERSION" >> $GITHUB_OUTPUT


      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            k0wojtasinski/mimicry:${{ steps.get_version.outputs.version }}
            k0wojtasinski/mimicry:latest
