name: Create Release

on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write # Needed to push commits and tags
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - uses: googleapis/release-please-action@v4
        id: release
        with:
          release-type: python
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
      
      - uses: astral-sh/setup-uv@v5
        name: Setup uv
        with:
          version: '0.7.13'
        if: steps.release.outputs.release_created
      
      - run: uv run mkdocs gh-deploy --force
        name: Deploy documentation
        if: steps.release.outputs.release_created

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        if: steps.release.outputs.release_created

      - name: Log in to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
        if: steps.release.outputs.release_created

      - name: Get tag version without 'v' prefix
        id: get_version
        run: |
          # Extract the version from the release tag
          VERSION=$(echo "${{ steps.release.outputs.release_tag }}" | sed 's/^v//')
          echo "version=${VERSION}" >> $GITHUB_OUTPUT
        if: steps.release.outputs.release_created

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            k0wojtasinski/mimicry:${{ steps.get_version.outputs.version }}
            k0wojtasinski/mimicry:latest
        if: steps.release.outputs.release_created
